#!/data/data/com.termux/files/usr/bin/bash
set -e
echo "=== FIXING VCAMSX UI PATCH ==="
# ---------------------------------------------------------
# 1. RESTORE the accidental EGL corruption
# ---------------------------------------------------------
find app/src/main/java -type f -name "*.kt" -print0 |
while IFS= read -r -d '' f; do
    sed -i 's/EGL_ACCENT_SIZE/EGL_ALPHA_SIZE/g' "$f"
done
echo "[+] Restored EGL_ALPHA_SIZE"
# ---------------------------------------------------------
# 2. REMOVE the duplicate Color.kt definitions
#    Restore the original file from git when possible.
# ---------------------------------------------------------
COLOR="app/src/main/java/com/wangyiheng/vcamsx/ui/theme/Color.kt"
if git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
    if git ls-files --error-unmatch "$COLOR" >/dev/null 2>&1; then
        git checkout -- "$COLOR"
        echo "[+] Restored Color.kt from git"
    fi
fi
# ---------------------------------------------------------
# 3. If Color.kt is still duplicated, rewrite it cleanly.
# ---------------------------------------------------------
cat > "$COLOR" <<'KOT'
package com.wangyiheng.vcamsx.ui.theme
import androidx.compose.ui.graphics.Color
// ============================================================
// VCAMSX REFERENCE PALETTE
// ============================================================
val CyberBlack = Color(0xFF0A0E17)
val CyberDeep = Color(0xFF0A0E17)
val CyberCard = Color(0xFF111622)
val CyberCardAlt = Color(0xFF10141E)
val CyberBorder = Color(0x3300E5FF)
val NeonCyan = Color(0xFF00E5FF)
val TechCyan = Color(0xFF00E5FF)
// Keep legacy accent names pointing to the SAME reference cyan.
val NeonGreen = Color(0xFF00E5FF)
val NeonOrange = Color(0xFF00E5FF)
val NeonPurple = Color(0xFF00E5FF)
val CyberText = Color(0xFFFFFFFF)
val CyberSubtext = Color(0xFF9299A6)
val CyberDim = Color(0xFF56606E)
val TextPrimary = Color(0xFFFFFFFF)
val TextSecondary = Color(0xFF9299A6)
val TextMuted = Color(0xFF56606E)
val SurfaceDark = Color(0xFF111622)
val SurfaceElevated = Color(0xFF10141E)
val ObsidianBg = Color(0xFF0A0E17)
val GlassBorder = Color(0x3300E5FF)
val GlassBorderFocus = Color(0xFF00E5FF)
val InputBg = Color(0x0DFFFFFF)
val InputBorder = Color(0x2AFFFFFF)
// Error remains red because it is semantic, not decoration.
val NeonRed = Color(0xFFFF5268)
// Material compatibility
val Purple80 = Color(0xFFFFFFFF)
val PurpleGrey80 = Color(0xFF9299A6)
val Pink80 = Color(0xFF9299A6)
val Purple40 = Color(0xFF00E5FF)
val PurpleGrey40 = Color(0xFF9299A6)
val Pink40 = Color(0xFF00E5FF)
KOT
echo "[+] Rebuilt Color.kt with ONE definition per color"
# ---------------------------------------------------------
# 4. Remove accidental duplicate ReferencePalette if it
#    was generated by the previous patch.
# ---------------------------------------------------------
REF="app/src/main/java/com/wangyiheng/vcamsx/ui/theme/ReferencePalette.kt"
if [ -f "$REF" ]; then
    rm -f "$REF"
    echo "[+] Removed temporary ReferencePalette.kt"
fi
# ---------------------------------------------------------
# 5. Check for EGL corruption anywhere else.
# ---------------------------------------------------------
if grep -Rni "EGL_ACCENT_SIZE" app/src/main 2>/dev/null; then
    echo "[!] EGL_ACCENT_SIZE still exists!"
    exit 1
fi
# ---------------------------------------------------------
# 6. Check duplicate declarations in Color.kt.
# ---------------------------------------------------------
echo
echo "=== COLOR CHECK ==="
grep -nE \
'val (TechCyan|NeonCyan|TextPrimary|TextSecondary|CyberCard|ObsidianBg)' \
"$COLOR"
# ---------------------------------------------------------
# 7. BUILD
# ---------------------------------------------------------
echo
echo "=== BUILDING ==="
./gradlew :app:assembleDebug
echo
echo "================================"
echo " VCAMSX BUILD SUCCESSFUL"
echo "================================"
