pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
        maven { url 'https://raw.githubusercontent.com/FBlackBox/FBlackBox/master/repo' }
    }
}

rootProject.name = "VCamRevived"
include ':app'
include ':hook'
